Models/ErrorViewModel.cs
using System;

namespace project.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace project.Controllers
{
    public class AboutMeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace project.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using project.Models;

namespace project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace project.Controllers
{
    public class mail : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace project.Controllers
{
    public class ResumeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace project.Controllers
{
    public class WorkController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/AboutMe/Index.cshtml
@{
    ViewData["Title"] = "About me";
}


<div class="text-center">
    <h1 class="display-4">About me</h1>
</div>

<hr />
<br />

<div class="container">
    <div class="row">
        <div class="col">
            <img src="/img/IMG_0718.jpg" alt="..." class="img-fluid rounded" style="border-color:#CD533B; border: 5px solid #CD533B;">
        </div>
        <div class="col" style="display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            width: 100%;
            text-align: center;
            align-items: center;">

            I am a computer science student at Clemson University preparing to graduate in December of 2021. During my time at
            Clemson I have had three internships, worked on numerous coding projects, and have learned more about computer science than I
            could have imagined. I am extremely exited
            for what is to come following graduation, and to see where my degree from Clemson takes me. Go Tigers!

        </div>
    </div>
</div>


<br />
<hr />
<br />

<div class="container">
    <div class="row">
        <div class="col" style="display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            width: 100%;
            text-align: center;
            align-items: center;">
            
            I enjoy travleing, the outdoors, and sports. I have been lucky enough to go hiking in places such as the Grand Canyon, the White Mountains of 
            New Hampshre, and the sand dunes of Michigan. I hope to one day visit all of the national parks in the United States. My favorite place
            I have traveled to is Italy, and I am excited to get back to traveling in the coming years. I am also a big fan of college football
            and college basketball, and love to cheer on the Clemson Tigers and the Louisville Cardinals. 

        </div>

        <div class="col" >

            <img src="/img/me4.jpg" alt="..." class="img-fluid rounded" style="border-color:#CD533B; border: 5px solid #CD533B;">

        </div>
    </div>
</div>

<br />
<hr />
<br />

<div class="container">
    <div class="row">
        <div class="col">
            <img src="/img/me2.jpg" alt="..." class="img-fluid rounded" style="border: 5px solid #CD533B;">
        </div>
        <div class="col align-items-center" style="display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            width: 100%;
            text-align: center;
            align-items: center;">

            <p>I was born and raised in Louisville, Kentucky and I graduated from Kentuky Country Day High School in 2017. In high school I played baseball for four years, 
            and I was on the swim team for three years. Before high school I also played soccer, basketball, and tennis. Growing up playing sports
            has taught me countless life lessons and has given me endless great memories that I hold dear to this day.</p>

        </div>
    </div>
</div>

Views/Contact/Index.cshtml
<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact me!</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">
        
    </p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-12 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="Resume" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->
                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->
                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <form action="Mail">
                    <input type="submit" value="Send!" />
                </form></div>
            <div class="status"></div>
        </div>

        
        <!--Grid column-->
        <!--Grid column-->
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Aaron Lattis</h1>


</div>
    
<hr />

<p class="text-center">Computer Science major with internship experience working on software development teams. 
    Highly motivated individual eager to learn on the job. </p>

<br />

<img src="/img/headshot1.PNG" class="rounded-circle mx-auto d-block" alt="" style="border: 5px solid #CD533B;">

<br />

Views/Resume/Index.cshtml
@{
    ViewData["Title"] = "Work expierence";
}


<div class="text-center">
    <h1 class="display-4">Work expierence</h1>
</div>

<hr />

<br />

<div style="margin:auto">
    <a href="/resume/Resume.pdf" download class="btn" style="background-color:#CD533B; display:block; margin: auto; width:18%">Download full resume <i class="fas fa-download"></i></a>
</div>

<br />

<br />


<div class="card mx-auto" style="width:60%;">

    <div class="card-header" style="background-color:#CD533B">

        Intern, eBlu Solutions, Louisville, Kentucky<br />May 2021 - August 2021

    </div>

    <div class="card-body">

        <ul>
            <li>Participated in daily stand up meetings with a software team of 8 co-workers</li>
            <li>Wrote and tested C# code to complete various user stories and improve the eBlu portal</li>
            <li>Used Amazon DevOps and Git to collaborate with the entire software team</li>
            <li>Completed 20 side projects to improve skills in C#, HTML, .NET programming, and the MVC framework</li>
        </ul>


    </div>

</div>

<br />
<br />

<div class="card mx-auto" style="width:60%;">

    <div class="card-header" style="background-color:#CD533B">

        Co-Op, Itron, West Union, South Carolina<br />January 2020 - August 2020

    </div>

    <div class="card-body">

        <ul>
            <li>Monitored 7 routers for various errors using PuTTY, and reported findings to the firmware team on a daily basis</li>
            <li>Wrote and maintained bash scripts to assist with daily testing as well as other activities</li>
            <li>Ensured that bug fixes were behaving as expected following new builds</li>
            <li>Flashed new builds onto 16 routers weekly, and ensured units were configured correctly</li>
            <li>Successfully transitioned to a remote work environment due to the Covid-19 pandemic</li>

        </ul>

    </div>

</div>

<br />
<br />

<div class="card mx-auto" style="width:60%;">

    <div class="card-header" style="background-color:#CD533B">

        Intern, Stansteel and Hotmix Parts, Louisville, Kentucky<br />July 2018 - August 2018

    </div>

    <div class="card-body">

        <ul>
            <li>Contacted clients and potential clients to update customer records and acquire new business</li>
            <li>Gathered information regarding a number of asphalt plants through internet research</li>
            <li>Compiled weekly reports to keep sales representatives up to date with my findings</li>

        </ul>

    </div>

</div>




@*<div class="text-center">
        <a href="/resume/Resume.pdf" download>
            <img src="/resume/Resume.PNG" alt="Resume" class="align-content-center">
        </a>
    </div>*@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Aaron Lattis - @ViewData["Title"]</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:#292F36;">
    <div>
        <header>
            <div>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3 container" style="background-color:#E9D2C0">
                    <div class="container">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AboutMe" asp-action="">About me</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Work" asp-action="">Past projects</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Resume" asp-action="">Work expierence</a>
                                </li>
                                <li class="nav-item ml-auto">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="">Contact <i class="fas fa-envelope"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
    </div>

        <div class="container" style="background-color:#E9D2C0;">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    

    <footer>
        <div class="container">
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Work/Index.cshtml
@{
    ViewData["Title"] = "Past projects";
}


<div class="text-center">
    <h1 class="display-4">Past projects</h1>
</div>

<hr />

<br />


<div class="card-deck">

    <div class="card" style="background-color:#CD533B">

        <img class="card-img-top" src="/img/engine1.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B">

            A player character that can run across the screen. Written in C++.

        </div>

        <a href="https://github.com/aaron-lattis/4160_PlayerCharacter" class="stretched-link" target="_blank"></a>

    </div>

    <div class="card"style="background-color:#CD533B">

        <img class="card-img-top" src="/img/truck1.jpg" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B">

            A website to track the performance of semi truck drivers. Written in Python, HTML, CSS, and other languages. 

        </div>

        <a href="https://github.com/aaron-lattis/4910_DiverIncentiveWebsite" class="stretched-link" target="_blank"></a>

    </div>
</div>

<br />
<br />

<div class="card-deck">

    <div class="card" style="background-color:#CD533B">

        <img class="card-img-top" src="/img/finalGame.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B">

            A video game where the player must avoid red dots to stay alive as long as possible. Written in C++.

        </div>

        <a href="https://github.com/aaron-lattis/4160_FinalVideoGame" class="stretched-link" target="_blank"></a>

    </div>

    <div class="card" style="background-color:#CD533B">

        <img class="card-img-top" src="/img/engine2.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B">

            A scene created using openGL and images from the internet. Written in C++.

        </div>

        <a href="https://github.com/aaron-lattis/4160_Drawing" class="stretched-link" target="_blank"></a>

    </div>
</div>


<br />
<br />

<div class="card-deck">

    <div class="card" style="background-color:#CD533B"> 

        <img class="card-img-top" src="/img/AI1.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B;">

            Play Connect 4 against an AI agent that uses minmax decision rules. Written in Python.

        </div>

        <a href="https://github.com/aaron-lattis/4420_Connect4AI" class="stretched-link" target="_blank"></a>

    </div>

    <div class="card" style="background-color:#CD533B">

        <img class="card-img-top" src="/img/405011.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B">

            An iterated function system used to create an image. Written in C++.

        </div>

        <a href="https://github.com/aaron-lattis/4040_IteratedFunctionSystem" class="stretched-link" target="_blank"></a>

    </div>
</div>

<br />
<br />

<div class="card-deck">

    <div class="card" style="background-color:#CD533B">

        <img class="card-img-top" src="/img/thiswebsite.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B;">

            This website! Check out the C#, HTML, and Bootstrap code used to create this website.

        </div>

        <a href="https://github.com/aaron-lattis/ENGL3040_Website" class="stretched-link" target="_blank"></a>

    </div>

    <div class="card" style="background-color:#CD533B">

        <img class="card-img-top" src="/img/40502.PNG" alt="Card image">

        <div class="card-footer" style="background-color:#CD533B">
            
            A simple ray tracer written in C++. 

        </div>

        <a href="https://github.com/aaron-lattis/4050_RayTracer" class="stretched-link" target="_blank"></a>

    </div>
</div>

<br />